-- 0008 — insert-only history of audit runs, so score trends and sparklines
-- are computed from real past runs instead of ever being fabricated.
-- `seo_audits` stays a latest-snapshot cache (unchanged); this table is
-- append-only — a new row per (route, run) — and is never updated in place.

create table if not exists public.seo_audit_history (
  id          bigint generated by default as identity primary key,
  route       text not null,
  checked_at  timestamptz not null default now(),
  score       int not null,
  categories  jsonb not null default '{}'::jsonb
);

create index if not exists seo_audit_history_checked_at_idx on public.seo_audit_history (checked_at desc);
create index if not exists seo_audit_history_route_idx on public.seo_audit_history (route);

alter table public.seo_audit_history enable row level security;

drop policy if exists "admins read seo audit history" on public.seo_audit_history;
create policy "admins read seo audit history"
  on public.seo_audit_history for select
  to authenticated
  using (public.is_cms_admin());

drop policy if exists "admins insert seo audit history" on public.seo_audit_history;
create policy "admins insert seo audit history"
  on public.seo_audit_history for insert
  to authenticated
  with check (public.is_cms_admin());
