-- 0009 — Landing Page Builder foundation: CMS-authored marketing pages assembled
-- from a JSON document of registered block instances (see src/lib/pagebuilder/).
-- Same trust model as blog_posts: RLS gated by is_cms_admin(), no service-role key.

-- ── 1. landing_pages ──────────────────────────────────────────────────────
create table if not exists public.landing_pages (
  id                       uuid primary key default gen_random_uuid(),
  slug                     text not null unique,            -- stable /lp/<slug> address
  root_alias               text unique,                      -- optional root-level path, e.g. 'black-friday'
  title                    text not null,
  document                 jsonb not null default '{"version":1,"blocks":[]}'::jsonb,
  seo                      jsonb not null default '{}'::jsonb,
  published_at             timestamptz,
  is_template              boolean not null default false,
  created_from_template_id uuid references public.landing_pages (id) on delete set null,
  author_id                uuid references auth.users (id),
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  -- a corrupted slug ("foo/bar") once made a blog post unreachable; never again
  constraint landing_pages_slug_no_slash check (slug !~ '/'),
  constraint landing_pages_root_alias_no_slash check (root_alias is null or root_alias !~ '/')
);

create index if not exists landing_pages_published_at_idx on public.landing_pages (published_at desc);

drop trigger if exists landing_pages_set_updated_at on public.landing_pages;
create trigger landing_pages_set_updated_at
  before update on public.landing_pages
  for each row execute function public.set_updated_at();

alter table public.landing_pages enable row level security;

-- Anyone may read published pages; drafts/scheduled (null or future published_at) are invisible.
drop policy if exists "public read published landing pages" on public.landing_pages;
create policy "public read published landing pages"
  on public.landing_pages for select
  to anon, authenticated
  using (published_at is not null and published_at <= now());

drop policy if exists "admins read all landing pages" on public.landing_pages;
create policy "admins read all landing pages"
  on public.landing_pages for select
  to authenticated
  using (public.is_cms_admin());

drop policy if exists "admins insert landing pages" on public.landing_pages;
create policy "admins insert landing pages"
  on public.landing_pages for insert
  to authenticated
  with check (public.is_cms_admin());

drop policy if exists "admins update landing pages" on public.landing_pages;
create policy "admins update landing pages"
  on public.landing_pages for update
  to authenticated
  using (public.is_cms_admin())
  with check (public.is_cms_admin());

drop policy if exists "admins delete landing pages" on public.landing_pages;
create policy "admins delete landing pages"
  on public.landing_pages for delete
  to authenticated
  using (public.is_cms_admin());

-- ── 2. landing_page_versions — append-only, mirrors seo_audit_history ─────
-- Autosave updates landing_pages.document in place; only initial creation,
-- publish, and an explicit "save version" checkpoint insert a row here, so
-- history doesn't fill with keystroke-adjacent noise.
create table if not exists public.landing_page_versions (
  id         bigint generated by default as identity primary key,
  page_id    uuid not null references public.landing_pages (id) on delete cascade,
  document   jsonb not null,
  seo        jsonb not null,
  label      text,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users (id)
);

create index if not exists landing_page_versions_page_id_idx
  on public.landing_page_versions (page_id, created_at desc);

alter table public.landing_page_versions enable row level security;

drop policy if exists "admins read landing page versions" on public.landing_page_versions;
create policy "admins read landing page versions"
  on public.landing_page_versions for select
  to authenticated
  using (public.is_cms_admin());

drop policy if exists "admins insert landing page versions" on public.landing_page_versions;
create policy "admins insert landing page versions"
  on public.landing_page_versions for insert
  to authenticated
  with check (public.is_cms_admin());

-- ── 3. global_sections — reusable mid-page blocks, referenced by id ───────
-- Table + BlockRenderer resolution ship now even though the authoring UI is a
-- later stage — resolving a reference is one cheap lookup, and this is the
-- "designed now, ships later" piece of the reusable-block architecture.
create table if not exists public.global_sections (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  type       text not null,
  props      jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

drop trigger if exists global_sections_set_updated_at on public.global_sections;
create trigger global_sections_set_updated_at
  before update on public.global_sections
  for each row execute function public.set_updated_at();

alter table public.global_sections enable row level security;

-- Public read: resolved during public page renders, not just admin edits.
drop policy if exists "public read global sections" on public.global_sections;
create policy "public read global sections"
  on public.global_sections for select
  to anon, authenticated
  using (true);

drop policy if exists "admins insert global sections" on public.global_sections;
create policy "admins insert global sections"
  on public.global_sections for insert
  to authenticated
  with check (public.is_cms_admin());

drop policy if exists "admins update global sections" on public.global_sections;
create policy "admins update global sections"
  on public.global_sections for update
  to authenticated
  using (public.is_cms_admin())
  with check (public.is_cms_admin());

drop policy if exists "admins delete global sections" on public.global_sections;
create policy "admins delete global sections"
  on public.global_sections for delete
  to authenticated
  using (public.is_cms_admin());

-- ── 4. redirects — minimal seed of a future standalone Redirect Manager ───
-- Auto-populated whenever a landing page's slug or root_alias changes, so old
-- links/backlinks/bookmarks don't silently 404. Same table would back a full
-- Redirect Manager module later — no throwaway work if that gets built.
create table if not exists public.redirects (
  id               bigint generated by default as identity primary key,
  source_path      text not null unique,
  destination_path text not null,
  status_code      int not null default 308,
  reason           text,
  landing_page_id  uuid references public.landing_pages (id) on delete set null,
  created_at       timestamptz not null default now()
);

alter table public.redirects enable row level security;

-- Public read: resolved on every unmatched public route, not just admin edits.
drop policy if exists "public read redirects" on public.redirects;
create policy "public read redirects"
  on public.redirects for select
  to anon, authenticated
  using (true);

drop policy if exists "admins insert redirects" on public.redirects;
create policy "admins insert redirects"
  on public.redirects for insert
  to authenticated
  with check (public.is_cms_admin());

drop policy if exists "admins update redirects" on public.redirects;
create policy "admins update redirects"
  on public.redirects for update
  to authenticated
  using (public.is_cms_admin())
  with check (public.is_cms_admin());

drop policy if exists "admins delete redirects" on public.redirects;
create policy "admins delete redirects"
  on public.redirects for delete
  to authenticated
  using (public.is_cms_admin());
